# import necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

# Import dataset from google colab

In [ ]:
from google.colab import files
a=files.upload()

Saving loan_small.csv to loan_small.csv


# Descriptive Analysis/EDA

In [ ]:
df=pd.read_csv('loan_small.csv')

In [ ]:
df

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0   LP001002     NaN           5849.0                0.0         NaN  urban   
1   LP001003    Male           4583.0                NaN       128.0   semi   
2   LP001005    Male           3000.0                0.0        66.0    NaN   
3   LP001006  Female           2583.0             2358.0       120.0   semi   
4   LP001008    Male              NaN                0.0       141.0  urban   
5   LP001011    Male           5417.0             4196.0       267.0   semi   
6   LP001013    Male           2333.0             1516.0         NaN  rural   
7   LP001014  Female           3036.0             2504.0       158.0   semi   
8   LP001018    Male           4006.0             1526.0       168.0  rural   
9   LP001020    Male          12841.0            10968.0       349.0   semi   
10  LP001024  Female           3200.0              700.0        70.0  urban   
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              NaN             8106.0         NaN  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
0            Y  
1            N  
2            Y  
3          NaN  
4            Y  
5            Y  
6            Y  
7            N  
8            Y  
9            N  
10           Y  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [ ]:
df.tail()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
11  LP001027    Male           2500.0             1840.0       109.0  urban   
12  LP001028  Female              NaN             8106.0         NaN  urban   
13  LP001029    Male           1853.0             2840.0       114.0  urban   
14  LP001030    Male           1299.0             1086.0        17.0   semi   
15  LP001032    Male           4950.0                0.0       125.0   semi   

   Loan_Status  
11           Y  
12           Y  
13           N  
14           Y  
15           Y

In [ ]:
df.head()

Loan_ID  Gender  ApplicantIncome  CoapplicantIncome  LoanAmount   Area  \
0  LP001002     NaN           5849.0                0.0         NaN  urban   
1  LP001003    Male           4583.0                NaN       128.0   semi   
2  LP001005    Male           3000.0                0.0        66.0    NaN   
3  LP001006  Female           2583.0             2358.0       120.0   semi   
4  LP001008    Male              NaN                0.0       141.0  urban   

  Loan_Status  
0           Y  
1           N  
2           Y  
3         NaN  
4           Y

In [ ]:
df.columns

Index(['Loan_ID', 'Gender', 'ApplicantIncome', 'CoapplicantIncome',
       'LoanAmount', 'Area', 'Loan_Status'],
      dtype='object')

In [ ]:
df.shape

(16, 7)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            16 non-null     object 
 1   Gender             15 non-null     object 
 2   ApplicantIncome    14 non-null     float64
 3   CoapplicantIncome  15 non-null     float64
 4   LoanAmount         13 non-null     float64
 5   Area               15 non-null     object 
 6   Loan_Status        15 non-null     object 
dtypes: float64(3), object(4)
memory usage: 1.0+ KB


In [ ]:
df.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount
count        14.000000          15.000000   13.000000
mean       4103.571429        2509.333333  140.923077
std        2858.096481        3147.982090   86.032418
min        1299.000000           0.000000   17.000000
25%        2520.750000         350.000000  109.000000
50%        3118.000000        1526.000000  125.000000
75%        4858.250000        2672.000000  158.000000
max       12841.000000       10968.000000  349.000000

# Null value deduction

In [ ]:
df.isnull().sum()

Gender               0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Area                 0
Loan_Status          0
dtype: int64

# Removing less important features

In [ ]:
df = df.dropna(subset=['Loan_Status'])

In [ ]:
df = df.drop(['Loan_ID'],axis=1)

In [ ]:
num = ['ApplicantIncome','CoapplicantIncome','LoanAmount']

In [ ]:
df[num] = df[num].fillna(df[num].mean())

In [ ]:
catg = ['Gender','Area']
df[catg] = df[catg].fillna(df.mode().iloc[0])

# Using LabelEncoder from sklearn library to change from categorical column to numerical column.

In [ ]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()

In [ ]:
df['newGender'] = lb.fit_transform(df['Gender'])
df['newArea'] = lb.fit_transform(df['Area'])
df['newLoan_Status'] = lb.fit_transform(df['Loan_Status'])

In [ ]:
df.drop('Gender',axis=1,inplace=True)
df.drop('Area',axis=1,inplace=True)
df.drop('Loan_Status',axis=1,inplace=True)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 15
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   ApplicantIncome    15 non-null     float64
 1   CoapplicantIncome  15 non-null     float64
 2   LoanAmount         15 non-null     float64
 3   newGender          15 non-null     int64  
 4   newArea            15 non-null     int64  
 5   newLoan_Status     15 non-null     int64  
dtypes: float64(3), int64(3)
memory usage: 840.0 bytes


# x and y split

In [ ]:
x = df.iloc[:,0:5]
y = df.iloc[:,-1]

# we going to perform NORMALISATION to improve the data for the model learning

In [ ]:
from sklearn import preprocessing
normalized_x = preprocessing.normalize(x)

In [ ]:
normalized_x

# TRIAN_TEST_SPLIT

In [ ]:
from sklearn.model_selection import train_test_split
normalized_x_train,normalized_x_test,y_train,y_test = train_test_split(normalized_x,y,test_size=0.3,random_state=23)

# We use SVM to train the datset

In [ ]:
from sklearn.svm import SVC
svm = SVC()
svm.fit(normalized_x_train,y_train)

SVC()

In [ ]:
ypredict = svm.predict(normalized_x_test)

#  Evaluation metrics for the SVM algorithm

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score
cmsvm = confusion_matrix(y_test,ypredict)
recall = recall_score(y_test,ypredict)
accuracy=accuracy_score(y_test,ypredict)
precision = precision_score(y_test,ypredict)
f1score = f1_score(y_test,ypredict)
print('CONFUSION METRICS','\n',cmsvm)
print()
print('RECALLSCORE    = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('    F1SCORE    = ',f1score)

CONFUSION METRICS 
 [[0 0]
 [4 1]]

RECALLSCORE    =  0.2
ACCURACYSCORE  =  0.2
PRECISIONSCORE =  1.0
    F1SCORE    =  0.33333333333333337


# KNN algorithm

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(normalized_x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_predict = knn.predict(normalized_x_test)

# Evaluation metrics for the KNN algorithm

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score
cmknn = confusion_matrix(y_test,y_predict)
recall = recall_score(y_test,y_predict)
accuracy = accuracy_score(y_test,y_predict)
precision = precision_score(y_test,y_predict)
f1score = f1_score(y_test,y_predict)
print('CONFUSIONMETRICS  ','\n',cmknn)
print()
print(' RECALLSCORE   = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('   F1SCORE     = ',f1score)

CONFUSIONMETRICS   
 [[0 0]
 [4 1]]

 RECALLSCORE   =  0.2
ACCURACYSCORE  =  0.2
PRECISIONSCORE =  1.0
   F1SCORE     =  0.33333333333333337


# **Logistical regression**

In [ ]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(random_state=0)
log_reg.fit(normalized_x_train,y_train)

LogisticRegression(random_state=0)

In [ ]:
y_predict = log_reg.predict(normalized_x_test)

In [ ]:
from sklearn.metrics import confusion_matrix,recall_score,accuracy_score,precision_score,f1_score
cmlog_reg =  confusion_matrix(y_test,y_predict)
recall = recall_score(y_test,y_predict)
accuracy = accuracy_score(y_test,y_predict)
precision = precision_score(y_test,y_predict)
f1score = f1_score(y_test,y_predict)
print('CONFUSION METRICS   ','\n',cmlog_reg)
print()
print(' RECALLSCORE   = ',recall)
print('ACCURACYSCORE  = ',accuracy)
print('PRECISIONSCORE = ',precision)
print('    F1SCORE    = ',f1score)

CONFUSION METRICS    
 [[0 0]
 [1 4]]

 RECALLSCORE   =  0.8
ACCURACYSCORE  =  0.8
PRECISIONSCORE =  1.0
    F1SCORE    =  0.888888888888889
